#ifndef _PROJECT_CONFIG_H_
#define _PROJECT_CONFIG_H_

#define PROJECT_NAME Tutorial
#define PROJECT_VERSION "0.1.1\0"
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 1

#endif
